version: '3'

services:
  db:
    image: postgres
    ports: 
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=somepassword
      - POSTGRES_DB=development_db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/onacu
    ports:
      - "8000:8000"
    depends_on:
      - db