# Generated by Django 2.2.12 on 2020-05-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_event_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eve_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
