# Generated by Django 2.2.12 on 2020-05-13 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20200511_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='person_max',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='event',
            name='purchaced_ticket',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='personal_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
