# Generated by Django 2.2.12 on 2020-05-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20200513_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='person_max',
        ),
        migrations.RemoveField(
            model_name='event',
            name='purchaced_ticket',
        ),
    ]
