# Generated by Django 2.2.12 on 2020-05-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_ticket_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='purchaced_ticket',
            field=models.IntegerField(default=0),
        ),
    ]
