# Generated by Django 2.2.12 on 2020-05-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_event_purchaced_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
