# Generated by Django 2.2.12 on 2020-05-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='peerId',
            field=models.CharField(default='0', max_length=16),
        ),
    ]
