# Generated by Django 2.2.12 on 2020-05-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_ticket_peerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
