# Generated by Django 2.2.12 on 2020-05-25 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_event_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='order',
        ),
        migrations.AlterField(
            model_name='event',
            name='personal_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
