# Generated by Django 2.2.12 on 2020-05-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
