# Generated by Django 2.2.13 on 2020-06-05 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20200601_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(help_text='この項目は必須です。例: 2020-07-01 13:00', verbose_name='開催日時'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='この項目は任意です。', null=True, upload_to='', verbose_name='イメージ画像'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='この項目は必須です。100文字以内にしてください。例: ○田□花 握手会', max_length=100, verbose_name='イベント名'),
        ),
        migrations.AlterField(
            model_name='event',
            name='personal_time',
            field=models.IntegerField(help_text='この項目は必須です。5秒以上、300秒以下にしてください。', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)], verbose_name='1人あたりの時間（秒）'),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_ticket',
            field=models.IntegerField(help_text='この項目は必須です。1枚以上、120枚以下にしてください。', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='チケット発行数'),
        ),
    ]
